---
title: "About us"
description: |
  We are a team based at the 
  [London School of Hygiene & Tropical Medicine](https://www.lshtm.ac.uk) who 
  focus on real-time modelling and forecasting of infectious disease outbreaks. 
  We are funded by the Wellcome Trust and work in collaboration with a number of
  other research groups, public health agencies and non-governmental
  organisations. Our main aim is to develop and use modelling methodology that
  makes the most of available resources to provide insights useful for outbreak
  response, control and prevention. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
```

```{r}
team <- fs::dir_ls("_data/team", regexp = "\\w+\\-\\w+\\.yml") %>%
  purrr::map(yaml::read_yaml)

# Put Seb first (group leader)
team <- c(
  team[which(purrr::map(team, "name") == "Sebastian Funk")],
  team[-which(purrr::map(team, "name") == "Sebastian Funk")]
)
```

## The team

```{r}
current_team <- team %>%
  purrr::keep(function(x) x[["current-member"]])
```

```{r, results='asis'}
current_team %>%
  purrr::map_chr(function(e) {
    knitr::knit_expand(
      "_team_member.Rmd", 
      name = e[["name"]],
      webpage = e[["webpage"]],
      github = e[["github"]],
      twitter = e[["twitter"]],
      orcid = e[["orcid"]],
      description = e[["description"]]
    )
  }) %>%
  { knitr::knit_child(text = unlist(.), quiet = TRUE) } %>%
  cat(sep = "\n")
```

## Former team members

```{r, results='asis'}
former_team <- team %>%
  purrr::keep(function(x) !x[["current-member"]]) %>%
  purrr::map_chr(function(e) {
    if (is.null(e[["webpage"]]) || e[["webpage"]] == "") {
      return(e[["name"]])
    } else {
      return(glue::glue('[{e[["name"]]}]({e[["webpage"]]})'))
    }
  }) %>%
  cat(sep = " · ")
```
